version: 0.1

phases:
  install:
    commands:
      - echo Entering install phase...
      - echo Nothing to do now
  build:
    commands:
      - echo Build started on `date`
      - chmod +x gradlew
      - ./gradlew assemble
      - chmod +x build/libs/coders-0.0.1-SNAPSHOT.jar
artifacts:
  type: zip
  files:
    - 'build/libs/*.jar'
discard-paths: yes